### ISSUE TITLE
Change is_supported() to Throw an Exception for Unsupported Platforms

### ISSUE THREAD

**Issue by meta-boy** [CapSoftware/scap#24]
**Issue Overview**:
The `is_supported()` method in the library currently returns a boolean to indicate platform support. This approach, while straightforward, might not be the most effective for handling critical situations like unsupported platforms. Transitioning to an exception-based approach could offer clearer feedback and align with robust error handling practices.

**Proposed Change**:
- Refactor `is_supported()` to throw a custom exception (e.g., `UnsupportedPlatformException`) when it detects an unsupported platform.
- Update the documentation to reflect this change and provide guidelines on how to handle this new exception.
- Ensure the change is communicated effectively to library users with clear migration instructions.

**Rationale**:
- **Improved Error Handling**: Throwing an exception can provide more detailed information and context about the failure, aiding in more effective debugging and logging.
- **Consistency in Library Design**: If the library predominantly uses exceptions for error handling, this modification will maintain consistency in design philosophy.
- **Enhanced Safety and Reliability**: By preventing further execution on unsupported platforms, we enhance the overall safety and reliability of the library.

**Broader Utility**:
- This change also enables the broader use of the `is_supported()` check within the library. It can act as a gateway to conditionally enable or disable certain functionalities based on platform compatibility. This ensures that each part of the library behaves appropriately according to the platform's capabilities, enhancing robustness and user experience.

**Impact on Users**:
- Users of the library will need to update their code to handle this new exception type. Providing comprehensive guidance is essential for a smooth transition.

**Comment by NiiightmareXD** [comment]
I can't entirely agree I think it is better if it returns `Result<bool, Error>` so if it fails to check for support it returns an error otherwise, it returns a bool that shows if it's supported or not.

Also about:
- Improved Error Handling: it doesn't because now every user should also check if it failed because it was unsupported or because it failed to check for support.
- Enhanced Safety and Reliability: how?

**Comment by clearlysid** [comment]
Aligned with @NiiightmareXD's feedback.

Another reason why (imo) we need not add an exception here is because an unsupported platform is an intermediary state. We would eventually like to support all platforms where `scap` would be useful, and having this as boolean is much easier until we get there.

For platforms that are truly never going to be supported, the cargo targets will take care of informing the developer during install/compile-time.

Closing this for now, but the following feedback will definitely be incorporated as we work on the API design for `scap`.

> I think it is better if it returns Result<bool, Error>
