### ISSUE TITLE
Glitchy frames on Macbook's Built-in Displays

### ISSUE THREAD

**Issue by clearlysid** [CapSoftware/scap#3]
When running `cargo run` on a Macbook where the built-in display is set as the primary one, the image pixels seem to be extremely misaligned. On an external display, the result is correct and as-expected 🤔

Here is a reference, need to investigate and fix.

## Captured Frame
![captured-frame](https://github.com/clearlysid/cypher/assets/30227512/3f33e1a9-0cd6-4fc6-ae0c-86d563b4dcaf)

## Screenshot
![screenshot](https://github.com/clearlysid/cypher/assets/30227512/6816387d-3971-4f79-8ee2-2ee2c8bad3c4)

**Comment by NiiightmareXD** [comment]
I don't have a Macbook but the problem is likely because of [Image Stride](https://learn.microsoft.com/en-us/windows/win32/medfound/image-stride) I had this problem in [windows-capture](https://github.com/NiiightmareXD/windows-capture) and the padding at the end of each row of pixels should be removed.

My distorted image kinda looked like this so I believe that's the problem.

**Comment by clearlysid** [comment]
Thanks for the insight and link, you were absolutely right — the stride was indeed the problem. After accounting for it I'm able to get a proper image out of mac and now just need to figure out quality and getting rid of that ugly green stride 🎉

![frame_397321647908](https://github.com/clearlysid/cypher/assets/30227512/46826a41-7fdb-4af9-b39e-e920b6ea14db)
padding.
